#!/bin/bash
#
# distro-module-manager        start/stop/status script
#
# chkconfig: - 64 36
# description: The distro-module-manager to manage modules for india distro
# processname: distro-module-manager
# config: /etc/default/distro-module-manager
# pidfile: /var/run/distro-module-manager/distro-module-manager.pid
### BEGIN INIT INFO
# Provides: distro-module-manager
# Required-Start: $local_fs $remote_fs $network $named $syslog $time
# Required-Stop: $local_fs $remote_fs $network $named $syslog $time
# Short-Description: start and stop distro-module-manager system,
# Description: INDIA DISTRO
### END INIT INFO

export DISTRO_MODULE_MANAGER_USER=bahmni
export DISTRO_MODULE_MANAGER_RUN=/opt/distro-module-manager/bin/start.sh
export CUR_USER=`/usr/bin/whoami`

# load configuration
. /etc/default/distro-module-manager

create_dirs() {
    if [[ ! -e /var/run/distro-module-manager ]]; then
        ln -s /opt/distro-module-manager/var /var/run/distro-module-manager
    fi

    if [[ ! -e /var/log/distro-module-manager ]]; then
        mkdir /var/log/distro-module-manager
    fi
}
distro_module_manager_pid() {
        echo `ps -fe | grep "distro-module-manager.jar" | grep -v grep | tr -s " "|cut -d" " -f2`
}

start(){
    pid=$(distro_module_manager_pid)
    if [ -n "$pid" ]
    then
        echo -e "\e[00;31mService distro-module-manager is already running (pid: $pid)\e[00m"
    else
        # Start distro-module-manager
        create_dirs
        echo -e "\e[00;32mStarting distro-module-manager\e[00m"
        if [ `user_exists $DISTRO_MODULE_MANAGER_USER` = "1" ]  && [ "$CUR_USER" != "$DISTRO_MODULE_MANAGER_USER" ] ;
        then
                /bin/su $DISTRO_MODULE_MANAGER_USER -c $DISTRO_MODULE_MANAGER_RUN
        else
                sh $DISTRO_MODULE_MANAGER_RUN
        fi
  fi
  return 0
}
status(){
          pid=$(distro_module_manager_pid)
          if [ -n "$pid" ]; then echo -e "\e[00;32mService distro-module-manager is running with pid: $pid\e[00m"
          else echo -e "\e[00;31mService distro-module-manager is not running\e[00m"
          fi
}

stop() {
	echo -e "\e[00;31mTerminating distro-module-manager\e[00m"
	kill -9 $(distro_module_manager_pid)
}
user_exists(){
        if id -u $1 >/dev/null 2>&1; then
        echo "1"
        else
                echo "0"
        fi
}

case $1 in
	start)
	  start
	;;
	stop)
	  stop
	;;
	restart)
	  stop
	  start
	;;
	status)
		status
	;;
	kill)
		stop
	;;
	*)

	;;
esac
exit 0
